---
- hosts: localhost

  tasks:
    - include_vars: vars.yaml

    - name: Use API Token if defined
      set_fact:
        authorization: "Bearer {{ api_token }}"
      when: api_token is defined

    - name: Use username/password if defined
      set_fact:
        authorization: "Basic {{ (username + ':' + password) | b64encode }}"
      when: username is defined and password is defined

    - name: Create cosign integration
      url:
        uri: "https://{{ api_endpoint }}/v1/signatureintegrations"
        method: POST
        validate_certs: no
        headers:
          authorization: "{{ authorization }}"
        body_format: json
        body: "{{ cosign_integration }}"
        status_code: [200]
      register: cosign_reponse

    - name: Create image policy
      url:
        uri: "https://{{ api_endpoint }}/v1/signatureintegrations"
        method: POST
        validate_certs: no
        headers:
          authorization: "{{ authorization }}"
        body_format: json
        body: "{{ image_signing_policy }}"
        status_code: [200]
      register: cosign_reponse
