---
- hosts: localhost
  gather_facts: no

  vars:
    ansible_remote_tmp: /runner/.ansible/tmp

  tasks:
    - include_vars: vars.yaml

    - name: Use API Token if defined
      set_fact:
        authorization: "Bearer {{ api_token }}"
      when: api_token is defined

    - name: Use username/password if defined
      set_fact:
        authorization: "Basic {{ (username + ':' + password) | b64encode }}"
      when: username is defined and password is defined

    - name: Create cosign integration
      ansible.builtin.uri:
        url: "https://{{ api_endpoint }}/v1/signatureintegrations"
        method: POST
        validate_certs: no
        headers:
          authorization: "{{ authorization }}"
        body_format: json
        body: "{{ cosign_integration }}"
        status_code: [200,409]

    # Have to see if policy exists manually since it returns a 500 rather then 409
    # for duplicated policies unlike signature integrations. Likely a bug IMHO
    - name: Retrieve list of policies
      ansible.builtin.uri:
        url: "https://{{ api_endpoint }}/v1/policies"
        method: GET
        validate_certs: no
        headers:
          authorization: "{{ authorization }}"
        status_code: [200]
      register: policy_list

    # - name: Output policy list result
    #   debug:
    #     msg: "{{ policy_list.json }}"

    - name: Extract policy already exists
      set_fact:
        trusted_signature_policy: "{{ policy_list.json | community.general.json_query(policy_query) }}"
      vars:
        policy_query: "policies[?name=='Trusted Signature Policy']"

    # - name: Output policy already exists
    #   debug:
    #     msg: "{{ trusted_signature_policy }}"

    - name: Create image policy
      ansible.builtin.uri:
        url: "https://{{ api_endpoint }}/v1/policies"
        method: POST
        validate_certs: no
        headers:
          authorization: "{{ authorization }}"
        body_format: json
        body: "{{ image_signing_policy }}"
        status_code: [200]
      when: not trusted_signature_policy

    - name: Setup image integration with Quay
      ansible.builtin.uri:
        url: "https://{{ api_endpoint }}/v1/imageintegrations"
        method: POST
        validate_certs: no
        headers:
          authorization: "{{ authorization }}"
        body_format: json
        body: "{{ quay_image_integration }}"
        status_code: [200, 400]
      register: integration_result

    - name: Output integration result
      debug:
        msg: "{{ integration_result }}"
