---
- hosts: localhost
  gather_facts: no

  vars:
    ansible_remote_tmp: /runner/.ansible/tmp

  tasks:
    - name: Use username/password if defined
      set_fact:
        authorization: "Basic {{ (username + ':' + password) | b64encode }}"

    - name: Get local-cluster id
      ansible.builtin.uri:
        url: "https://{{ api_endpoint }}/v1/clusters"
        method: GET
        validate_certs: no
        headers:
          authorization: "{{ authorization }}"
        status_code: [200]
      register: clusters

    - name: Cosign integration
      herve4m.rhacs_configuration.rhacs_signature:
        name: cosign
        skip_validate_certs: true
        cosign_pub_keys:
          - name: cosign.pub
            key: "{{ lookup('ansible.builtin.file', 'cosign.pub') }}"
        state: present
        rhacs_host: "{{ api_endpoint }}"
        rhacs_username: admin
        rhacs_password: "{{ password }}"
      register: cosign_integration

    - name: Trusted Signature Policy
      herve4m.rhacs_configuration.rhacs_policy:
        skip_validate_certs: true
        policy: Trusted Signature Policy
        state: present
        rhacs_host: "{{ api_endpoint }}"
        rhacs_username: admin
        rhacs_password: "{{ password }}"
        data:
          name: Trusted Signature Policy
          description: Validate image signatures
          rationale: ''
          remediation: ''
          disabled: false
          categories:
          - Security Best Practices
          - Supply Chain Security
          lifecycleStages:
          - BUILD
          - DEPLOY
          eventSource: NOT_APPLICABLE
          exclusions: []
          severity: HIGH_SEVERITY
          enforcementActions:
          - FAIL_BUILD_ENFORCEMENT
          - SCALE_TO_ZERO_ENFORCEMENT
          - UNSATISFIABLE_NODE_CONSTRAINT_ENFORCEMENT
          notifiers: []
          scope:
          - cluster: "{{clusters.json.clusters[0].id}}"
            namespace: user.*-dev,user.*-stage,user.*-prod
          SORTName: Trusted Signature Policy
          SORTLifecycleStage: BUILD,DEPLOY
          SORTEnforcement: true
          policyVersion: '1.1'
          policySections:
          - sectionName: Rule 1
            policyGroups:
            - fieldName: Image Signature Verified By
              booleanOperator: OR
              negate: false
              values:
              - value: "{{ cosign_integration.id }}"
          mitreAttackVectors: []
          criteriaLocked: false
          mitreVectorsLocked: false
          isDefault: false
          source: IMPERATIVE

    - name: Configure Quay Registry Integration
      herve4m.rhacs_configuration.rhacs_image_integration:
        skip_validate_certs: true
        name: Quay
        type: quay
        run_test: false
        quay:
          category: REGISTRY
          quay_host: registry-quay-quay-operator.{{ subdomain }}
        state: present
        rhacs_host: "{{ api_endpoint }}"
        rhacs_username: admin
        rhacs_password: "{{ password }}"

    - name: Disable Fixable Important Severity Policy
      herve4m.rhacs_configuration.rhacs_policy:
        skip_validate_certs: true
        policy: Fixable Severity at least Important
        state: present
        rhacs_host: "{{ api_endpoint }}"
        rhacs_username: admin
        rhacs_password: "{{ password }}"
        data:
          name: Fixable Severity at least Important
          description: Alert on deployments with fixable vulnerabilities with a Severity Rating at least Important
          rationale: |-
            Known vulnerabilities make it easier for adversaries to exploit your application.
            You can fix these high-severity vulnerabilities by updating to a newer version of
            the affected component(s).
          remediation: |-
            Use your package manager to update to a fixed version in future builds
            or speak with your security team to mitigate the vulnerabilities.
          disabled: true
          categories:
          - Vulnerability Management
          lifecycleStages:
          - BUILD
          - DEPLOY
          eventSource: NOT_APPLICABLE
          exclusions: []
          scope: []
          severity: HIGH_SEVERITY
          enforcementActions:
          - FAIL_BUILD_ENFORCEMENT
          notifiers: []
          lastUpdated: '2025-01-21T18:36:42.078780032Z'
          SORTName: Fixable Severity at least Important
          SORTLifecycleStage: BUILD,DEPLOY
          SORTEnforcement: true
          policyVersion: '1.1'
          policySections:
          - sectionName: ''
            policyGroups:
            - fieldName: Fixed By
              booleanOperator: OR
              negate: false
              values:
              - value: ".*"
            - fieldName: Severity
              booleanOperator: OR
              negate: false
              values:
              - value: ">=IMPORTANT"
          mitreAttackVectors: []
          criteriaLocked: true
          mitreVectorsLocked: true
          isDefault: true
          source: IMPERATIVE
